POST http://localhost:9527/register
Content-Type: application/json

{
  "username": "carcar",
  "password": "carcar"
}


###
POST http://localhost:9527/login
Content-Type: application/json

{
  "username": "carcar",
  "password": "carcar"
}

###
GET http://localhost:9527/search-car-no?car_no=car-5edf429b54e30
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXJfbm8iOiJjYXItNWVkZjQyOWI1NGUzMCIsImlkIjoxLCJ1c2VybmFtZSI6ImNhcmNhciJ9.lpB46NBzxEPm6ofX8AytzmTjjRV5KAYdAV0tBKM9_PU

