version: '3.1'

services:
  etcd:
    image: consul:latest
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0 -enable-script-checks
    volumes:
      - ./data:/consul/data
    ports:
      - 8500:8500
      - "8600:8600/udp"
      - 2381:2380